config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
  }
  devise_for :clients, controllers: {
    registrations: "clients/registrations",
    sessions: "clients/sessions",
    confirmations: "clients/confirmations",
    mailer: "clients/mailer",
    passwords: "clients/passwords",
    shared: "clients/shared",
    unlocks: "clients/unlocks",
  }
  scope module: :clients do
    root 'products#top'
    # 商品
    resources :products, only: %i(show index)
    get 'genres/:id/genre_products' => 'products#genre_products'
    # 注文
    post "orders/pre_create" => "orders#pre_create"
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/after_order" => "orders#after_order"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "clients/withdrawal" => "clients#withdrawal"
    patch "clients/withdrawal" => "clients#withdrawal"
    resources :clients, only: [:show, :edit, :update, :destroy]
    # カート
    resources :inside_carts, only: [:create, :index, :update, :destroy]
    delete 'inside_carts' => 'inside_carts#destroy_all'
    # 登録先住所
    resources :shipping_addresses, only: %i(new create edit update destroy)
  end
  namespace :admins do
    root 'orders#top'
    # 商品
    resources :products, only: %i(new show create edit index update)
    # 注文
    get "orders/top" => "orders#top"
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/product_orders_status" => "orders#product_orders_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: %i(create index update edit)
    # カート
    resources :inside_carts, only: [:update]
    # 会員
    resources :clients, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'search' => 'searches#search'
  end
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admins/genres_controller.rb
# frozen_string_literal: true

class Admins::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admins_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
      flash[:success] = "編集に成功しました"
    else
      flash[:danger] = "編集に失敗しました"
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_enabled)
  end
end

app/helpers/admins/genres_helper.rb
# frozen_string_literal: true

module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<div class="row">
<%# 下記変更済み（飯田） %>
<h2 class="genre-edit-head">ジャンル編集</h2>
<%= form_for(@genre, url: admins_genre_path(@genre),html: {method: "patch"}) do |genre| %>

	<%= genre.text_field :name %>
	<label>
	<%= genre.radio_button :is_enabled, :true %>有効
	</label>
	<label>
	<%= genre.radio_button :is_enabled, :false %>無効
	</label>
	<%= genre.submit '変更を保存する',class:"btn btn-success genre-submit" %>
<%# ここまで %>
<% end %>
</div>

app/views/admins/genres/index.html.erb
<div class="row">
<h2>ジャンル一覧・追加</h2>

<%= form_for(@genre, url:'/admins/genres') do |f| %>

	<p>ジャンル</p>
	<%= f.text_field :name %>

	<label><%= f.radio_button :is_enabled, "true" %>有効</label>　
	<label><%= f.radio_button :is_enabled, "false" %>無効</label>

	<%= f.submit '追加', class: 'btn btn-primary' %>
<%end%>

<table class="table table-bordere">
	<thead>
		<tr>
			<th>ジャンル</th>
			<th>状態</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<% @genres.each do |genre| %>
			<tr>
				<td><%= genre.name %></td>
				<td>
					<% if genre.is_enabled == true %>
  							有効
					<% else %>
   							無効
 					<% end %>
 				</td>
				<td><%= link_to "編集する", edit_admins_genre_path(genre.id), class: 'btn btn-success' %></td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>