config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
  }
  devise_for :clients, controllers: {
    registrations: "clients/registrations",
    sessions: "clients/sessions",
    confirmations: "clients/confirmations",
    mailer: "clients/mailer",
    passwords: "clients/passwords",
    shared: "clients/shared",
    unlocks: "clients/unlocks",
  }
  scope module: :clients do
    root 'products#top'
    # 商品
    resources :products, only: %i(show index)
    get 'genres/:id/genre_products' => 'products#genre_products'
    # 注文
    post "orders/pre_create" => "orders#pre_create"
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/after_order" => "orders#after_order"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "clients/withdrawal" => "clients#withdrawal"
    patch "clients/withdrawal" => "clients#withdrawal"
    resources :clients, only: [:show, :edit, :update, :destroy]
    # カート
    resources :inside_carts, only: [:create, :index, :update, :destroy]
    delete 'inside_carts' => 'inside_carts#destroy_all'
    # 登録先住所
    resources :shipping_addresses, only: %i(new create edit update destroy)
  end
  namespace :admins do
    root 'orders#top'
    # 商品
    resources :products, only: %i(new show create edit index update)
    # 注文
    get "orders/top" => "orders#top"
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/product_orders_status" => "orders#product_orders_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: %i(create index update edit)
    # カート
    resources :inside_carts, only: [:update]
    # 会員
    resources :clients, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'search' => 'searches#search'
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_paranoid

  has_many :shipping_addresses, dependent: :destroy
  has_many :inside_carts, dependent: :destroy
  has_many :products, through: :inside_carts
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :street_address, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/ }
  # アカウント作成時の電話番号はハイフンなしの10桁もしくは11桁のみ登録可能とするバリデーション
  validates :first_name_kana, :last_name_kana, presence: true, format: { with: /\A([ァ-ン]|ー)+\z/, message: "is must NOT contain any other characters than alphanumerics." }
  # アカウント作成時の苗字名前のカナ入力欄のカタカナのみ入力可能とするバリデーション
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  # アカウント作成時の郵便番号はハイフンなしの7桁のみ登録可能とするバリデーション

  # 書き直しました（飯田）
  # 検索機能（部分検索）
  def self.search(word)
    Client.where(["first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%"])
  end
  # ここまで
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/inside_cart.rb
# frozen_string_literal: true

class InsideCart < ApplicationRecord
  belongs_to :client
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  belongs_to :client

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }
  enum order_status: {
    "入金待ち" => 0,
    "入金確認" => 1,
    "製作中" => 2,
    "発送準備中" => 3,
    "発送済み" => 4,
  }
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :genre
  has_many :inside_carts, dependent: :destroy
  has_many :clients, through: :inside_carts
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  attachment :image

  validates :image, presence: true
  validates :name, presence: true
  validates :explanation, presence: true
  validates :genre_id, presence: true
  # 値段設定時、半角数字のみ登録可能にするバリデーション
  validates :price, presence: true, format: {
    with: /\A[0-9]+\z/i,
  }

  # 検索機能（部分検索）
  def self.search(word)
    Product.where("name LIKE?", "%#{word}%")
  end
end

app/models/product_order.rb
# frozen_string_literal: true

class ProductOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product

  enum order_status: {
    "着手不可" => 0,
    "製作待ち" => 1,
    "制作中" => 2,
    "製作完了" => 3,
  }
end

app/models/shipping_address.rb
# frozen_string_literal: true

class ShippingAddress < ApplicationRecord
  belongs_to :client

  with_options presence: true do
    validates :receive_name
    validates :street_address
  end

  validates :postal_code, format: { with: /\A\d{7}\z/ }
  # アカウント作成時の郵便番号はハイフンなしの7桁のみ登録可能とするバリデーション

  def full_address
    [postal_code, street_address, receive_name].join('')
  end
end

app/controllers/admins/searches_controller.rb
# class SearchesController < ApplicationController
class Admins::SearchesController < ApplicationController
  def search
    @range = params[:range]
    # search = params[:search]
    @word = params[:word]
    # 論理削除済の顧客を含めてsearchするために.with_deletedを追記しました。byけんちゃん
    if @range == '1'
      @clients = Client.with_deleted.search(@word)
    elsif @range == '2'
      @products = Product.search(@word)
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    case resource
    when Client
      root_path
    when Admin
      admins_root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :postal_code, :street_address])
  end
end

app/helpers/admins/clients_helper.rb
# frozen_string_literal: true

module Admins::ClientsHelper
end

app/helpers/admins/genres_helper.rb
# frozen_string_literal: true

module Admins::GenresHelper
end

app/helpers/admins/orders_helper.rb
# frozen_string_literal: true

module Admins::OrdersHelper
end

app/helpers/admins/products_helper.rb
# frozen_string_literal: true

module Admins::ProductsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients/clients_helper.rb
# frozen_string_literal: true

module Clients::ClientsHelper
end

app/helpers/clients/inside_carts_helper.rb
# frozen_string_literal: true

module Clients::InsideCartsHelper
end

app/helpers/clients/orders_helper.rb
# frozen_string_literal: true

module Clients::OrdersHelper
end

app/helpers/clients/products_helper.rb
# frozen_string_literal: true

module Clients::ProductsHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/searches/_search.html.erb
<div class="search-window">
  <%= form_tag(admins_search_path, method: :get) do %>
    <%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['会員名', '1'], ['商品名', '2']]) %>
    <%= text_field_tag (:word) %>
    <%= submit_tag "検索" %>
  <% end %>
</div>

app/views/admins/searches/search.html.erb
<div class="container">
  <!--product一覧 -->
  <% if @range == '2' %>
    <% if @products.count > 0 %>
      <h2>' <%= @word %> 'の商品が <%= @products.count %>件見つかりました</h2>
      <table class="table table-hover table-inverse">
      <thead>
        <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= link_to product.name, admins_product_path(product) %></td>
          <td><%= product.price %></td>
          <td><%= product.genre.name %></td>
          <td>
            <% if product.is_enabled  == true %>
            販売中
            <% else %>
            販売停止中
            <% end %>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
     <% else %>
      <h2> ' <%= @word %> 'の商品は見つかりませんでした</h2>
     <% end %>
  <%# clients一覧  %>
  <% else %>
    <% if @clients.count > 0 %>
      <h2>' <%= @word %> 'の会員が <%= @clients.count %>名見つかりました</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |client| %>
            <tr>
              <td><%= client.id %></td>
              <td><%= client.first_name %><%= client.last_name %></td>
              <td><%= client.email %></td>
              <td><% if client.deleted_at == nil %>
                  有効会員
              <% else %>
                  無効会員
              <% end %>
              </td>
              <td><%= link_to "Show", admins_client_path(client) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
    <h2> ' <%= @word %> 'の会員は見つかりませんでした</h2>
    <% end %> 
  <% end %>
</div>